# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.101

    - name: Print environment information
      run: |
        echo "Current working directory: $PWD"
        echo "GitHub Workspace: $GITHUB_WORKSPACE"

    - name: List directory structure
      run: ls -R ClassLibraryProjects/

    - name: Restore dependencies
      run: dotnet restore ClassLibraryProjects/ClassLibraryProjects.sln

    - name: Build
      run: dotnet build ClassLibraryProjects/ClassLibraryProjects.sln --no-restore

    - name: Test
      run: dotnet test ClassLibraryProjects/ClassLibraryProjects.sln --no-build --verbosity normal
